### ISSUE TITLE
Smart contract for v0.3

### ISSUE THREAD

**Issue by ChialiT** [State-Channel-4/contracts-poc2#1]
https://hackmd.io/@2y-oUv8rRpi6mYk9sSHOcw/BkWjEV5O2

**Comment by tpantpan** [comment]
2 issues related to this @NicoSerranoP, plz update, ty!

**Comment by NicoSerranoP** [comment]
Implement this: [https://hackmd.io/@2y-oUv8rRpi6mYk9sSHOcw/BkWjEV5O2](https://hackmd.io/@2y-oUv8rRpi6mYk9sSHOcw/BkWjEV5O2)

The smart contract distribution and architecture is here: [https://www.figma.com/file/fVNtk4IxFvwGsaWJLSHjQd/Channel4Contract.sol?type=whiteboard&node-id=0%3A1&t=NkDONU2w5wtdCEdk-1](https://www.figma.com/file/fVNtk4IxFvwGsaWJLSHjQd/Channel4Contract.sol?type=whiteboard&node-id=0%3A1&t=NkDONU2w5wtdCEdk-1)


- [x] Implement createContent
- [x] Implement createTag
- [x] Implement toggleLike
- [x] Implement litigateContent
- [x] Implement litigateTag
- [x] Implement litigateLike
- [x] Implement litigateNumberOfLikes
- [ ] Implement block timestamp to prevent inmediate litigations
