### ISSUE TITLE
[Incentives]: Create a ERC-20 token for stablecoin

### ISSUE THREAD

**Issue by NicoSerranoP** [State-Channel-4/contracts-poc2#10]
There is no testnet stablecoin contract so we will need to deploy one following the ERC-20 token standard. The idea behind it is to deploy it using a external public address and then assign funds to the contract (it would act as a "donation"). Then implement the following functions:

- [ ] Create and deploy ERC-20
- [ ] Function to change contract address (only backend can do this)
- [ ] Implement `receiveDonations` that receives ETH and then swaps it with the stablecoin (ERC-20)
- [ ] Send funds when `withdrawRewards` is called
- [ ] Function to get available funds (stablecoin) of the `Channel4Contract`

**Comment by NicoSerranoP** [comment]
@hackertron take a look at it 😊 . I will start working on #9 but after it I can continue with this issue as well (if you are busy doing other stuff)

**Comment by ChialiT** [comment]
no stablecoin, or our own erc-20
